name: deploy website

on:
  workflow_dispatch:
  push:
    branches: [ main]
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.OJ}}  #Required
          vercel-project-id: ${{ secrets.PJ}} #Required
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.OD2}}  #Required
          vercel-project-id: ${{ secrets.PD2}} #Required           